apiVersion: v2
name: gitdata-ai
description: Install gitdata.ai to provide gitdata official web page.
version: 1.0.0
kubeVersion: < 1.28.0-0
home: https://gitdata.ai/
keywords:
  - gitdata-ai
sources:
  - https://github.com/GitDataAI/website
maintainers:
  - name: gitdata team
